version: "3.9"

services:
  bot:
    build: ./Redirect-Bot/
    container_name: redirectbot
    restart: unless-stopped
    environment:
    - DC_token=${DISCORD_BOT_TOKEN:-yourtokenhere}
    - DISCORD_BOT_ACTIVITY=${DISCORD_BOT_ACTIVITY:-I'm alive!}
    - DISCORD_BOT_COMMAND_PREFIX=${DISCORD_BOT_COMMAND_PREFIX:-!}